package cards

import (
	"path/filepath"
	"slices"
	"testing"
)

func TestRepositoryKnowledgeCardsImportWithoutErrors(t *testing.T) {
	knowledgeDir := filepath.Clean(filepath.Join("..", "..", "..", "knowledge"))

	result, err := ScanDirectories([]string{knowledgeDir})
	if err != nil {
		t.Fatalf("scan failed: %v", err)
	}

	if len(result.Errors) != 0 {
		t.Fatalf("expected no import errors, got %d", len(result.Errors))
	}

	expectedIDs := []string{
		"docker-build-image",
		"docker-compose-down-services",
		"docker-compose-exec-service-shell",
		"docker-compose-logs-service-output",
		"docker-compose-up-services",
		"docker-env-file-variables",
		"docker-exec-running-container",
		"docker-images-local-images",
		"docker-logs-container-output",
		"docker-network-container-network",
		"docker-port-mapping-host-container",
		"docker-ps-running-containers",
		"docker-rm-remove-container",
		"docker-run-start-container",
		"docker-stop-stop-container",
		"docker-volume-persist-data",
		"http-cookie-vs-session-state",
		"http-get-safe-read",
		"http-grpc-binary-rpc",
		"http-header-metadata-carrier",
		"http-content-type-media-type",
		"http-http1-connection-model",
		"http-http2-multiplexing",
		"http-http3-quic-transport",
		"http-idempotent-request-semantics",
		"http-jwt-stateless-token",
		"http-keep-alive-connection-reuse",
		"http-post-create-submit",
		"http-put-vs-patch-update",
		"http-rest-resource-style",
		"http-status-code-families",
		"http-tcp-reliable-transport",
		"http-tls-handshake-trust-setup",
		"http-tls-encrypted-channel",
		"http-udp-datagram-transport",
		"git-add-staging",
		"git-branch-list",
		"git-checkout-legacy",
		"git-cherry-pick-purpose",
		"git-clone-local-copy",
		"git-commit-snapshot",
		"git-diff-compare",
		"git-fetch-basic",
		"git-init-repository",
		"git-log-history",
		"git-merge-purpose",
		"git-merge-conflict-resolution",
		"git-pull-composition",
		"git-push-upstream",
		"git-rebase-vs-merge",
		"git-rebase-continue-flow",
		"git-remote-origin",
		"git-revert-safe-undo",
		"git-reset-head",
		"git-restore-discard",
		"git-stash-purpose",
		"git-status-purpose",
		"git-switch-branch",
		"git-tag-release-marker",
		"go-channel-communication",
		"go-defer-late-execution",
		"go-error-value-handling",
		"go-error-wrapping-context",
		"go-goroutine-concurrency",
		"go-interface-nil-trap",
		"go-interface-behavior-contract",
		"go-context-cancellation",
		"go-map-key-value",
		"go-package-module-boundary",
		"go-pointer-memory-address",
		"go-receiver-method-binding",
		"go-slice-dynamic-view",
		"go-struct-field-grouping",
		"go-struct-tag-metadata",
		"backend-async-backpressure-pressure",
		"backend-cache-aside-pattern",
		"backend-cache-invalidation-hard-problem",
		"backend-create-new-resource",
		"backend-crud-resource-basics",
		"backend-delete-remove-resource",
		"backend-eventual-consistency-delay",
		"backend-e2e-test-full-journey",
		"backend-flaky-test-instability",
		"backend-integration-test-boundary",
		"backend-cache-ttl-expiration-window",
		"backend-hot-key-cache-skew",
		"backend-mock-test-double",
		"backend-queue-async-work-buffer",
		"backend-race-condition-shared-state",
		"backend-read-fetch-resource",
		"backend-retry-transient-failure-policy",
		"backend-soft-delete-hide-not-drop",
		"backend-stub-fixed-response-double",
		"backend-sync-vs-async-flow",
		"backend-timeout-fail-fast-guard",
		"backend-unit-test-small-scope",
		"backend-update-change-resource",
		"backend-write-through-vs-write-back",
		"bash-and-vs-or-command-chain",
		"bash-command-substitution",
		"bash-exit-code-status",
		"bash-export-env-var",
		"bash-path-command-lookup",
		"bash-shell-vs-env-variable",
		"linux-cat-print-file",
		"linux-cd-change-directory",
		"linux-chmod-permissions",
		"linux-cp-copy-files",
		"linux-find-search-files",
		"linux-grep-search-text",
		"linux-kill-stop-process",
		"linux-ls-list-files",
		"linux-mv-move-rename",
		"linux-pipe-command-chain",
		"linux-ps-process-list",
		"linux-pwd-current-directory",
		"linux-redirect-output-file",
		"linux-tail-file-end",
		"linux-wc-count-lines-words",
		"linux-xargs-build-arguments",
		"middleware-auth-check-gate",
		"middleware-before-vs-after",
		"middleware-cors-browser-policy",
		"middleware-logging-cross-cutting",
		"middleware-order-chain-effects",
		"middleware-request-pipeline-layer",
		"middleware-short-circuit-response",
		"sql-explain-plan-inspect",
		"sql-acid-transaction-guarantees",
		"sql-full-table-scan-cost",
		"sql-group-by-bucket",
		"sql-having-post-group-filter",
		"sql-index-speed-lookup",
		"sql-indexed-where-fast-filter",
		"sql-inner-vs-left-join",
		"sql-join-match-rows",
		"sql-join-too-many-cost",
		"sql-left-join-where-trap",
		"sql-limit-top-n",
		"sql-missing-where-update-risk",
		"sql-null-comparison-trap",
		"sql-order-by-sort-rows",
		"sql-count-star-aggregate",
		"sql-select-read-columns",
		"sql-select-star-overfetch",
		"sql-where-filter-rows",
		"sql-where-vs-having-trap",
		"python-class-blueprint-object",
		"python-comprehension-compact-loop",
		"python-context-manager-with",
		"python-decorator-wrap-function",
		"python-dict-key-value",
		"python-dunder-init-constructor",
		"python-exception-try-except",
		"python-generator-lazy-iteration",
		"python-import-module-loading",
		"python-iterator-next-protocol",
		"python-lambda-anonymous-function",
		"python-list-vs-tuple",
		"python-module-vs-package-boundary",
		"python-set-unique-values",
		"python-venv-pip-install-flow",
		"python-venv-isolation",
	}

	importedIDs := make([]string, 0, len(result.Cards))
	for _, card := range result.Cards {
		importedIDs = append(importedIDs, card.ID)
	}

	for _, expectedID := range expectedIDs {
		if !slices.Contains(importedIDs, expectedID) {
			t.Fatalf("expected repository card %q to exist", expectedID)
		}
	}
}
