// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function CheckAndSendNotification():Promise<boolean>;

export function GetStudyCard(arg1:string):Promise<main.StudyCard>;

export function LoadDashboard():Promise<main.DashboardData>;

export function SnoozeNotifications():Promise<void>;

export function SubmitAnswer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SubmitAnswerResult>;
