// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CheckAndSendNotification() {
  return window['go']['main']['App']['CheckAndSendNotification']();
}

export function ExitApplication() {
  return window['go']['main']['App']['ExitApplication']();
}

export function GenerateDraftScaffold(arg1, arg2) {
  return window['go']['main']['App']['GenerateDraftScaffold'](arg1, arg2);
}

export function GetDGReaction(arg1) {
  return window['go']['main']['App']['GetDGReaction'](arg1);
}

export function GetStudyCard(arg1) {
  return window['go']['main']['App']['GetStudyCard'](arg1);
}

export function InteractWithDG() {
  return window['go']['main']['App']['InteractWithDG']();
}

export function LoadAuthoringPreview() {
  return window['go']['main']['App']['LoadAuthoringPreview']();
}

export function LoadAuthoringPrompt() {
  return window['go']['main']['App']['LoadAuthoringPrompt']();
}

export function LoadDashboard() {
  return window['go']['main']['App']['LoadDashboard']();
}

export function PreviewKnowledgeCard(arg1) {
  return window['go']['main']['App']['PreviewKnowledgeCard'](arg1);
}

export function RescanKnowledge() {
  return window['go']['main']['App']['RescanKnowledge']();
}

export function ResetStudyData() {
  return window['go']['main']['App']['ResetStudyData']();
}

export function ReviewDraft(arg1) {
  return window['go']['main']['App']['ReviewDraft'](arg1);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveDraft'](arg1, arg2);
}

export function SendTestNotification() {
  return window['go']['main']['App']['SendTestNotification']();
}

export function SnoozeNotifications() {
  return window['go']['main']['App']['SnoozeNotifications']();
}

export function StartLearnBreak() {
  return window['go']['main']['App']['StartLearnBreak']();
}

export function SubmitAnswer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitAnswer'](arg1, arg2, arg3, arg4);
}

export function UpdateNotificationSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateNotificationSettings'](arg1, arg2);
}

export function UpdatePreferredLanguage(arg1) {
  return window['go']['main']['App']['UpdatePreferredLanguage'](arg1);
}

export function UpdateScheduleSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateScheduleSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSelectedTopic(arg1) {
  return window['go']['main']['App']['UpdateSelectedTopic'](arg1);
}

export function ValidateKnowledge() {
  return window['go']['main']['App']['ValidateKnowledge']();
}
