// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function CheckAndSendNotification():Promise<boolean>;

export function GetStudyCard(arg1:string):Promise<main.StudyCard>;

export function LoadAuthoringPreview():Promise<main.AuthoringPreviewData>;

export function LoadDashboard():Promise<main.DashboardData>;

export function PreviewKnowledgeCard(arg1:string):Promise<main.AuthoringPreviewData>;

export function RescanKnowledge():Promise<main.ActionStatus>;

export function ResetStudyData():Promise<main.ActionStatus>;

export function ReviewDraft(arg1:string):Promise<main.DraftReviewData>;

export function SaveDraft(arg1:string,arg2:string):Promise<main.SaveDraftStatus>;

export function SendTestNotification():Promise<main.ActionStatus>;

export function SnoozeNotifications():Promise<main.ActionStatus>;

export function SubmitAnswer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SubmitAnswerResult>;

export function UpdateNotificationSettings(arg1:string,arg2:string):Promise<main.ActionStatus>;

export function UpdatePreferredLanguage(arg1:string):Promise<main.ActionStatus>;

export function UpdateScheduleSettings(arg1:number,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<main.ActionStatus>;

export function ValidateKnowledge():Promise<main.ValidationStatus>;
