// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CheckAndSendNotification() {
  return window['go']['main']['App']['CheckAndSendNotification']();
}

export function GetStudyCard(arg1) {
  return window['go']['main']['App']['GetStudyCard'](arg1);
}

export function LoadDashboard() {
  return window['go']['main']['App']['LoadDashboard']();
}

export function RescanKnowledge() {
  return window['go']['main']['App']['RescanKnowledge']();
}

export function SendTestNotification() {
  return window['go']['main']['App']['SendTestNotification']();
}

export function SnoozeNotifications() {
  return window['go']['main']['App']['SnoozeNotifications']();
}

export function SubmitAnswer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitAnswer'](arg1, arg2, arg3, arg4);
}
